events {}

http {
    upstream auth_service      { server auth-service:8080; }
    upstream shortener_service { server shortener-service:8080; }
    upstream redirector_service { server redirector-service:8080; }
    upstream analytics_service { server analytics-service:8080; }
    upstream frontend           { server frontend:80; }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/shorten {
            proxy_pass http://shortener_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/my-links {
            proxy_pass http://shortener_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/stats/ {
            proxy_pass http://analytics_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /r/ {
            proxy_pass http://redirector_service;
            proxy_set_header Host $host;
        }

        location /health/ {
            proxy_pass http://$arg_service;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
        }
    }
}
